// The library of insights the reasoning layer (Claude) produces from Sprout signal.
// Categorized by insight type; tagged with KPI pillar, platform, model, and review status.

export type Platform = "instagram" | "facebook" | "tiktok" | "cross";
export type Severity = "opportunity" | "watch" | "alert";
export type Model = "Haiku 4.5" | "Sonnet";
export type Status = "new" | "reviewing" | "actioned";

export interface Category {
  id: string;
  label: string;
  blurb: string;
}

export const categories: Category[] = [
  { id: "competitive", label: "Competitive Intelligence", blurb: "Share of voice and detected competitor moves from web-wide listening." },
  { id: "content-gap", label: "Content Gaps", blurb: "Demand the current content plan is not answering." },
  { id: "anomaly", label: "Performance Anomalies", blurb: "Metrics moving faster or slower than the baseline expects." },
  { id: "trend", label: "Emerging Trends", blurb: "Topics rising in the DIY/tool space before they are obvious." },
  { id: "community", label: "Community Health", blurb: "Whether the audience engages back — comments, DMs, sentiment." },
  { id: "growth", label: "Audience Growth", blurb: "Follower and reach dynamics across the three platforms." },
];

export const pillars = [
  "Awareness", "Engagement", "Audience Growth", "Video Performance", "Content Performance", "Community Health",
] as const;

export interface Insight {
  id: string;
  category: string;
  severity: Severity;
  title: string;
  summary: string;
  why: string;
  platforms: Platform[];
  pillar: (typeof pillars)[number];
  model: Model;
  confidence: number;
  status: Status;
  delivered: string;
  actions: string[];
}

export const insights: Insight[] = [
  {
    id: "n01",
    category: "community",
    severity: "opportunity",
    title: "TikTok comment spike is purchase-intent, not applause",
    summary: "Comment volume +42% WoW on the ONE+ compatibility demo — but ~60% are questions about battery fit and where to buy.",
    why: "Sentiment is positive yet unresolved. Unanswered purchase questions decay within hours, so the window is short.",
    platforms: ["tiktok"],
    pillar: "Community Health",
    model: "Haiku 4.5",
    confidence: 0.86,
    status: "new",
    delivered: "07:52 today",
    actions: ["Reply to high-intent comments in the Sprout inbox", "Brief a compatibility tutorial for this week's slot"],
  },
  {
    id: "n02",
    category: "competitive",
    severity: "watch",
    title: "DEWALT launched a #WeekendBuild UGC push",
    summary: "Coordinated hashtag campaign across IG + TikTok — ~1,200 creator posts in 72 hours, share of voice rising on the build-project cluster.",
    why: "Listening flagged a synchronized volume surge outside RYOBI's owned channels. Early engagement is strong.",
    platforms: ["instagram", "tiktok"],
    pillar: "Awareness",
    model: "Haiku 4.5",
    confidence: 0.79,
    status: "reviewing",
    delivered: "07:52 today",
    actions: ["Draft a ONE+ ecosystem response angle for review", "Add #WeekendBuild to the listening watchlist"],
  },
  {
    id: "n03",
    category: "anomaly",
    severity: "alert",
    title: "Facebook engagement down 4% for a second week",
    summary: "Static product photos underperform; video and how-to formats retain 3x longer on the same audience.",
    why: "The decline is concentrated in single-image posts. The format, not the audience, is the variable that changed.",
    platforms: ["facebook"],
    pillar: "Content Performance",
    model: "Haiku 4.5",
    confidence: 0.83,
    status: "new",
    delivered: "07:52 today",
    actions: ["Shift 2 weekly static posts to short-form video", "A/B a how-to format against the current baseline"],
  },
  {
    id: "n04",
    category: "trend",
    severity: "opportunity",
    title: "\"Quiet cordless\" is an emerging search theme",
    summary: "Mentions of noise/decibel levels around cordless tools up 3.1x MoM in the DIY conversation, ahead of any RYOBI content.",
    why: "Trend detection surfaced a rising sub-topic with low competitor coverage — a first-mover content opening.",
    platforms: ["cross"],
    pillar: "Awareness",
    model: "Sonnet",
    confidence: 0.72,
    status: "new",
    delivered: "Monthly report",
    actions: ["Commission a decibel-comparison reel", "Test 'quiet' messaging in the next brand campaign"],
  },
  {
    id: "n05",
    category: "content-gap",
    severity: "opportunity",
    title: "No content answers \"is it available in Canada?\"",
    summary: "A recurring purchase-location question across TikTok and IG comments has zero corresponding owned content.",
    why: "The reasoning layer cross-referenced comment clusters against the content library and found no match.",
    platforms: ["tiktok", "instagram"],
    pillar: "Community Health",
    model: "Haiku 4.5",
    confidence: 0.81,
    status: "new",
    delivered: "07:52 today",
    actions: ["Publish a 'where to buy' carousel with retail partners", "Pin a stock-location comment on the demo post"],
  },
  {
    id: "n06",
    category: "growth",
    severity: "watch",
    title: "TikTok is the efficient growth engine",
    summary: "TikTok drives net-new followers at 2.7x the cost-efficiency of Facebook this period, at a 9.1% engagement rate.",
    why: "Follower growth per post far outpaces the other platforms while requiring less spend.",
    platforms: ["tiktok"],
    pillar: "Audience Growth",
    model: "Haiku 4.5",
    confidence: 0.88,
    status: "actioned",
    delivered: "Yesterday",
    actions: ["Reallocate 2 weekly slots from Facebook to TikTok", "Protect posting cadence at 4+/week"],
  },
  {
    id: "n07",
    category: "competitive",
    severity: "watch",
    title: "Milwaukee scaled short-form to 11 posts/week",
    summary: "Highest cadence in the tracked set, concentrated on jobsite build clips — a deliberate volume play.",
    why: "Competitor benchmark shows a step-change in posting frequency, not a one-off.",
    platforms: ["tiktok"],
    pillar: "Content Performance",
    model: "Haiku 4.5",
    confidence: 0.77,
    status: "new",
    delivered: "07:52 today",
    actions: ["Assess whether quality holds at higher cadence", "Do not match volume for its own sake — protect voice"],
  },
  {
    id: "n08",
    category: "community",
    severity: "alert",
    title: "Response time on DMs slipped past 6 hours",
    summary: "Median first-response time on Instagram DMs rose to 6h12m, above the 4h target during a high-intent window.",
    why: "Inbox volume surged with the ONE+ demo but staffing on the queue did not, risking lost purchase intent.",
    platforms: ["instagram"],
    pillar: "Community Health",
    model: "Haiku 4.5",
    confidence: 0.84,
    status: "reviewing",
    delivered: "07:52 today",
    actions: ["Enable an inbox rule to triage compatibility questions", "Draft AI-assisted FAQ replies for human approval"],
  },
  {
    id: "n09",
    category: "trend",
    severity: "opportunity",
    title: "Battery-ecosystem loyalty is a rising narrative",
    summary: "Conversation framing tools as an 'investment in one battery system' up sharply — favorable to the ONE+ story.",
    why: "Sentiment analysis at scale shows the ecosystem angle resonates more than single-tool specs.",
    platforms: ["cross"],
    pillar: "Engagement",
    model: "Sonnet",
    confidence: 0.75,
    status: "new",
    delivered: "Monthly report",
    actions: ["Lead the next campaign with the ONE+ ecosystem promise", "Feature multi-tool 'one battery' build stories"],
  },
  {
    id: "n10",
    category: "anomaly",
    severity: "opportunity",
    title: "Tuesday 6pm ET is an unusually strong slot",
    summary: "Posts published Tuesday early-evening outperform the weekly mean by 31% on saves and shares.",
    why: "Optimal-send-time data plus recent performance converge on an underused window.",
    platforms: ["instagram", "tiktok"],
    pillar: "Engagement",
    model: "Haiku 4.5",
    confidence: 0.8,
    status: "new",
    delivered: "07:52 today",
    actions: ["Move the flagship weekly post to Tuesday 6pm ET", "Reserve the slot for high-effort content"],
  },
  {
    id: "n11",
    category: "content-gap",
    severity: "watch",
    title: "Beginner-level content is thin vs. demand",
    summary: "First-time-buyer questions ('which drill should I start with?') outpace beginner-oriented posts 5:1.",
    why: "The library skews toward pro and enthusiast content while a large comment cohort is entry-level.",
    platforms: ["cross"],
    pillar: "Content Performance",
    model: "Sonnet",
    confidence: 0.73,
    status: "new",
    delivered: "Monthly report",
    actions: ["Launch a 'first tool' beginner series", "Tag beginner content for a dedicated highlight"],
  },
  {
    id: "n12",
    category: "growth",
    severity: "watch",
    title: "Facebook follower growth has plateaued",
    summary: "Net-new followers flat for three weeks while reach holds — an aging, non-expanding audience.",
    why: "Reach without follower growth suggests content is recirculating within the existing base.",
    platforms: ["facebook"],
    pillar: "Audience Growth",
    model: "Haiku 4.5",
    confidence: 0.78,
    status: "new",
    delivered: "Yesterday",
    actions: ["Test a lookalike-audience boost on top video", "Cross-promote the TikTok build series to Facebook"],
  },
  {
    id: "n13",
    category: "competitive",
    severity: "opportunity",
    title: "RYOBI holds share-of-voice lead on 'affordable pro'",
    summary: "34% category SoV overall, and a clear #1 on the value/pro price-performance keyword cluster.",
    why: "Listening share-of-voice breakdown shows a defensible position competitors are not contesting.",
    platforms: ["cross"],
    pillar: "Awareness",
    model: "Sonnet",
    confidence: 0.82,
    status: "actioned",
    delivered: "Monthly report",
    actions: ["Double down on price-performance proof content", "Claim the keyword cluster in paid social"],
  },
  {
    id: "n14",
    category: "anomaly",
    severity: "watch",
    title: "Reel completion rate dipped on 60s+ videos",
    summary: "Videos over 60 seconds lose 22% more viewers before the payoff than the 30–45s band.",
    why: "Video-performance data shows a clear length threshold where retention falls off.",
    platforms: ["instagram", "tiktok"],
    pillar: "Video Performance",
    model: "Haiku 4.5",
    confidence: 0.85,
    status: "new",
    delivered: "07:52 today",
    actions: ["Cap build clips at 45s where possible", "Front-load the payoff in the first 3 seconds"],
  },
  {
    id: "n15",
    category: "community",
    severity: "opportunity",
    title: "Three advocates worth activating identified",
    summary: "Listening surfaced three creators consistently posting positive ONE+ build content, unprompted and on-brand.",
    why: "UGC/advocate discovery matched sustained positive mentions above a follower and engagement threshold.",
    platforms: ["tiktok", "instagram"],
    pillar: "Engagement",
    model: "Sonnet",
    confidence: 0.7,
    status: "new",
    delivered: "Monthly report",
    actions: ["Have a human reach out to open a creator relationship", "Reshare their content with credit (with permission)"],
  },
  {
    id: "n16",
    category: "trend",
    severity: "watch",
    title: "Seasonal shift toward outdoor/yard projects",
    summary: "DIY conversation is rotating from indoor renovation to yard and garden builds as the season turns.",
    why: "Topic modeling shows a predictable seasonal migration starting two weeks earlier than last year.",
    platforms: ["cross"],
    pillar: "Content Performance",
    model: "Sonnet",
    confidence: 0.74,
    status: "new",
    delivered: "Monthly report",
    actions: ["Shift the content calendar toward outdoor projects", "Prepare a raised-garden-bed build for the ONE+ line"],
  },
];
